[package]
name = "nkandy44_fib_rs"
version = "0.1.0"
authors = ["Nadiminty Kaundinya <nkandy44@gmail.com>"]
edition = "2018"

[dependencies]


[lib]
name = "nkandy44_fib_rs"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
